flags: {}
extra-package-dbs: []
packages:
- .
- location: ./xmonad
  extra-dep: true
- location: ./xmonad-contrib
  extra-dep: true
extra-deps:
- X11-xft-0.3.1
resolver: lts-13.19
nix:
  packages:
    - pkgconfig
    - x11
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXScrnSaver
